#
# FastWay BBS - fpcmake configuration
# Based on LoraBBS by Marco Maccaferri. GPL v2 Licensed.
#
# Usage: fpcmake Makefile.fpc && make
#

[package]
name=fastwaybbs
version=1.0.0

[compiler]
options=-MObjFPC -Sh -O2
unitdir=common comm lora_api msgbase synapse
includedir=common

[target]
programs=tools/luser tools/lfile tools/lmsg tools/snoop

[clean]
files=$(wildcard units/$(CPU_TARGET)-$(OS_TARGET)/*.o) $(wildcard units/$(CPU_TARGET)-$(OS_TARGET)/*.ppu)

[install]
fpcpackage=n

[default]
fpcdir=/usr
