#
# FastWay BBS - fpcmake configuration
# Based on LoraBBS by Marco Maccaferri. GPL v2 Licensed.
#
# Usage: fpcmake Makefile.fpc && make
#

[package]
name=fastwaybbs
version=1.0.0

[require]
packages=fcl-base

[compiler]
options=-MObjFPC -Sh -O2
unitdir=common comm lora_api msgbase
includedir=common

[target]
programs=tools/luser tools/lfile tools/lmsg tools/snoop

[clean]
files=$(wildcard output/*.o) $(wildcard output/*.ppu) $(wildcard output/*.so) $(wildcard output/*.dll)

[install]
fpcpackage=n

[default]
fpcdir=.
